credentials:
  usernames:
    srini:
      email: shrini.tummala@gmail.com
      name: Srini Tummala
      password: "$2b$12$8TjiN8kB5bXubPzEyYyV9uYaIZIfWroXtgzPXEaM/iTprgedqYXk6"  # Welcome$123
    anindito:
      email: anindito.dee@wipro.com
      name: Anindito Dee
      password: "$2b$12$8TjiN8kB5bXubPzEyYyV9uYaIZIfWroXtgzPXEaM/iTprgedqYXk6"  # Welcome$123
    rajasekhar:
      email: rajasekhar.ramadas@wipro.com
      name: Rajasekhar Ramadas
      password: "$2b$12$8TjiN8kB5bXubPzEyYyV9uYaIZIfWroXtgzPXEaM/iTprgedqYXk6"  # Welcome$123

cookie:
  expiry_days: 7
  key: automate_iq_secret_key_2024
  name: automate_iq_auth

preauthorized:
  emails: []
